<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="fr">
<context>
    <name>DeleteProjectDialog</name>
    <message>
        <location filename="base/file/doDeleteProject.py" line="87"/>
        <source>Could not open geodatabase.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="base/file/doDeleteProject.py" line="100"/>
        <source>Error occured while deleting project in geodatabase.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="base/file/doDeleteProject.py" line="110"/>
        <source>Could not open projects database.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="base/file/doDeleteProject.py" line="118"/>
        <source>Error occured while deleting project in projects database.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="base/file/doDeleteProject.py" line="129"/>
        <source>Something went wrong while deleting project: </source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="base/file/doDeleteProject.py" line="134"/>
        <source>Project deleted. Please remove project directory manually.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>VeriSO</name>
    <message>
        <location filename="veriso.py" line="280"/>
        <source>&amp;VeriSO</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="veriso.py" line="147"/>
        <source>VeriSO</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="veriso.py" line="163"/>
        <source>Projects</source>
        <translation type="unfinished">Projets</translation>
    </message>
    <message>
        <location filename="veriso.py" line="171"/>
        <source>File</source>
        <translation type="unfinished">Fichier</translation>
    </message>
    <message>
        <location filename="veriso.py" line="173"/>
        <source>Import project</source>
        <translation type="unfinished">Importer projet</translation>
    </message>
    <message>
        <location filename="veriso.py" line="175"/>
        <source>Delete project</source>
        <translation type="unfinished">Effacer projet</translation>
    </message>
    <message>
        <location filename="veriso.py" line="185"/>
        <source>Settings</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="veriso.py" line="187"/>
        <source>Options</source>
        <translation type="unfinished">Options</translation>
    </message>
    <message>
        <location filename="veriso.py" line="276"/>
        <source>Error while loading application module: </source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
